[package]
name = "arb-mel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
# Internal crates
arbos = { workspace = true }
arb-primitives = { workspace = true }
arb-storage-errors = { workspace = true }

# Alloy
alloy-primitives = { workspace = true, features = ["std"] }
alloy-consensus = { workspace = true }

# Common
thiserror = { workspace = true }

[features]
default = ["std"]
std = []

[lints]
workspace = true
